name: Diary of a Small Town Pastor
favicon: null
layout_spectrum: 0.9971
typography_spectrum: 0.49324
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050f04'
    - '#fffce9'
    - '#b5d6f9'
    - '#807b65'
    - '#4c4c40'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
