name: Diary of a Small Town Pastor
favicon: null
layout_spectrum: 0.16855601174756885
typography_spectrum: 0.06326517625711858
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.050698916194960475
  lightness: 0.27048810152336955
  saturation: 0.445748581783846
  rhythmicContrast: 0.07779713231138885
purpose: []
